#!/usr/bin/env python3
"""Convert PassPony iOS's Localizable.xcstrings into Android string
resources for all seven supported languages.

Usage:
    python3 scripts/xcstrings_to_strings.py [--source PATH] [--check]

Design notes (see docs/plan/P13-localization.md for the packet spec):

- Source of truth is the iOS app's Localizable.xcstrings. Its top-level
  "strings" dict is keyed by the *English source text itself* (Apple's
  convention); a key with no "en" localization entry means the English
  value equals the key verbatim.

- Android already has a hand-authored app/src/main/res/values/strings.xml
  built up across packets P01-P12, using meaningful key names
  (settings_autofill_header, and so on) rather than generated ones. Many
  of those entries' English text is byte-identical to an xcstrings key
  (both apps share the same UI copy). For those, we reuse the *existing*
  Android resource name rather than manufacturing a new one -- this is
  the whole point of matching by value first: it lets translations land
  under the names Kotlin call sites already reference, with zero
  renaming. Only keys with no existing Android match get a generated
  name (snake_case slug of the English text, "xc_" prefixed so it reads
  as "imported from the shared corpus, not yet wired to any UI" until a
  later packet -- P14 onboarding, P16 storefront -- adds the screen that
  uses it and can rename it to something meaningful at that point).

- English resources are never regenerated wholesale: values/strings.xml
  keeps every hand-authored entry byte-for-byte. The script only
  *appends* a new grouped block for xcstrings-sourced keys that don't
  already exist under a matching name/value, so hand-picked keys are
  never disturbed and the diff stays reviewable.

- The other six locales (es, fr, de, ru, zh-Hans, pt-BR) don't exist yet,
  so those files are generated fresh, containing only the keys that
  actually have a translation in that language among the keys selected
  for English (matched or newly appended). Untranslated keys are simply
  omitted per locale -- Android's resource resolution falls back to the
  default values/ (English) automatically, matching the packet's stated
  "omit the key" policy for missing translations.

- Apple format specifiers (%@, %lld, %llu, and their %N$-positional
  forms) are converted to Android's %N$s / %N$d, always emitting an
  explicit position (Android's formatter requires one whenever a string
  has more than one argument, and using it unconditionally keeps output
  deterministic regardless of argument count). A bare, non-positional
  run of specifiers is numbered in the order encountered. Any literal
  '%' that survives outside a recognized specifier is doubled to '%%',
  but only in strings that contain at least one real format argument
  (a plain '%' with no arguments elsewhere doesn't need escaping, and
  doubling every '%' unconditionally would be wrong for a lone percent
  sign that just means the character itself).

- Escaping of the literal (non-format) text matches the house
  convention already used throughout strings.xml: apostrophes become
  \\', double quotes become \\", and the three XML metacharacters
  (& < >) are entity-escaped. No value is quote-wrapped.

- Output is deterministic: keys are emitted in sorted (name) order and
  the header comment is fixed text with no embedded timestamp, so a
  rerun against an unchanged source produces a byte-identical result
  (verify with --check, which reports a nonzero exit if regenerating
  would change anything already on disk).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPO_ROOT.parent / "PassPony" / "Sources" / "Shared" / "Localizable.xcstrings"
STRINGS_EN = REPO_ROOT / "app" / "src" / "main" / "res" / "values" / "strings.xml"
REPORT_PATH = REPO_ROOT / "scripts" / "xcstrings_mapping_report.txt"
NAME_MAP_PATH = REPO_ROOT / "scripts" / "xcstrings_name_map.json"

# xcstrings locale tag -> Android resource-directory qualifier.
LOCALE_DIRS = {
    "en": "values",
    "es": "values-es",
    "fr": "values-fr",
    "de": "values-de",
    "ru": "values-ru",
    "zh-Hans": "values-b+zh+Hans",
    "pt-BR": "values-b+pt+BR",
}
NON_ENGLISH = [tag for tag in LOCALE_DIRS if tag != "en"]

GENERATED_BLOCK_START = "    <!-- P13: imported from the shared iOS string corpus (Localizable.xcstrings) -->"
GENERATED_BLOCK_END = "    <!-- end P13 imported corpus -->"
GENERATED_HEADER = (
    "<!--\n"
    "  Generated by scripts/xcstrings_to_strings.py from\n"
    "  PassPony/Sources/Shared/Localizable.xcstrings. Do not hand-edit;\n"
    "  rerun the script and it will regenerate this file byte-for-byte.\n"
    "-->\n"
)

_STRING_NAME_RE = re.compile(r'<string name="([^"]+)">(.*?)</string>', re.S)
_PLURALS_NAME_RE = re.compile(r'<plurals name="([^"]+)"')

# --- format-specifier conversion ------------------------------------------

# Matches Apple format specifiers: an optional explicit position ("1$"),
# then the conversion. @ is "any object" (-> Android %s); lld/llu/ld/lu/d/u
# are integer forms (-> Android %d); f is float (-> Android %f).
_APPLE_SPEC_RE = re.compile(r"%(\d+\$)?(lld|llu|ld|lu|@|d|u|f)")

_ANDROID_TYPE = {
    "@": "s",
    "d": "d",
    "u": "d",
    "ld": "d",
    "lu": "d",
    "lld": "d",
    "llu": "d",
}


def convert_value(raw: str) -> str:
    """Convert one Apple-format, xcstrings-escaped value into an
    Android-format, strings.xml-escaped value."""
    specs = list(_APPLE_SPEC_RE.finditer(raw))
    has_format_args = bool(specs)

    out: list[str] = []
    pos = 0
    auto_index = 0
    for m in specs:
        literal = raw[pos : m.start()]
        out.append(_escape_literal(literal, has_format_args))
        explicit_pos = m.group(1)  # e.g. "1$" or None
        if explicit_pos:
            index = int(explicit_pos[:-1])
        else:
            auto_index += 1
            index = auto_index
        android_type = _ANDROID_TYPE[m.group(2)]
        out.append(f"%{index}${android_type}")
        pos = m.end()
    out.append(_escape_literal(raw[pos:], has_format_args))
    return "".join(out)


def _escape_literal(text: str, has_format_args: bool) -> str:
    if has_format_args:
        text = text.replace("%", "%%")
    text = xml_escape(text)  # & < >
    text = text.replace("'", "\\'").replace('"', '\\"')
    return text


# --- key naming -------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(source_text: str) -> str:
    slug = _SLUG_RE.sub("_", source_text.lower()).strip("_")
    if not slug:
        slug = "str"
    if len(slug) > 48:
        slug = slug[:48].rstrip("_")
    return f"xc_{slug}"


def unescape_android_value(value: str) -> str:
    """Reverse of _escape_literal's quote/apostrophe/XML escaping, for
    matching an existing strings.xml value back to xcstrings' raw key
    text. Does not need to reverse format-specifier conversion since we
    only use this to compare literal (non-format) source strings."""
    value = value.replace("\\'", "'").replace('\\"', '"')
    value = value.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
    return value


def load_existing_android_strings(path: Path) -> dict[str, str]:
    """value (unescaped) -> existing resource name, for every plain
    <string> in the given strings.xml. Plurals are intentionally not
    indexed here: none of the hand-authored entries are plurals today,
    and the xcstrings corpus's plural keys are matched by name only
    below."""
    if not path.exists():
        return {}
    content = path.read_text(encoding="utf-8")
    mapping: dict[str, str] = {}
    for name, value in _STRING_NAME_RE.findall(content):
        mapping[unescape_android_value(value)] = name
    return mapping


def existing_resource_names(path: Path) -> set[str]:
    if not path.exists():
        return set()
    content = path.read_text(encoding="utf-8")
    names = {n for n, _ in _STRING_NAME_RE.findall(content)}
    names |= set(_PLURALS_NAME_RE.findall(content))
    return names


def load_name_map(path: Path) -> dict[str, str]:
    """key_text -> previously assigned Android resource name, persisted
    across runs. This is the actual source of run-to-run stability: value
    matching against strings.xml (below) only works for keys with no
    format specifiers, since a key's Apple-format text ("Edit %@") never
    round-trips back from its Android-format value ("Edit %1$s"). Once a
    name is assigned -- whether adopted from an existing hand-authored
    key or freshly generated -- it is recorded here and reused verbatim
    forever after, independent of value matching or slug collisions."""
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def render_name_map(mapping: dict[str, str]) -> str:
    ordered = {k: mapping[k] for k in sorted(mapping)}
    return json.dumps(ordered, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


# --- xcstrings model helpers --------------------------------------------------


def entry_should_translate(entry: dict) -> bool:
    return entry.get("shouldTranslate", True) is not False


def string_unit_value(node: dict) -> str | None:
    unit = node.get("stringUnit")
    if unit and unit.get("value"):
        return unit["value"]
    return None


def plural_quantities(node: dict) -> dict[str, str] | None:
    plural = node.get("variations", {}).get("plural")
    if not plural:
        return None
    out = {}
    for quantity, qnode in plural.items():
        value = string_unit_value(qnode)
        if value:
            out[quantity] = value
    return out or None


def localized_value(entry: dict, lang: str, key_text: str) -> tuple[str, dict[str, str] | None] | None:
    """Returns (simple_value, None) or (None, plural_dict) for `lang`, or
    None if that language has no usable content for this key. English
    falls back to the key text itself when no "en" localization is
    present, matching xcstrings' own convention."""
    loc = entry.get("localizations", {}).get(lang)
    if loc is None:
        if lang == "en":
            return (key_text, None)
        return None
    simple = string_unit_value(loc)
    if simple is not None:
        return (simple, None)
    plural = plural_quantities(loc)
    if plural is not None:
        return (None, plural)
    if lang == "en":
        return (key_text, None)
    return None


# --- resource building --------------------------------------------------------


class Resource:
    __slots__ = ("name", "simple", "plural")

    def __init__(self, name: str, simple: str | None, plural: dict[str, str] | None):
        self.name = name
        self.simple = simple
        self.plural = plural


def build_resources_for_locale(
    lang: str,
    xc_strings: dict,
    key_to_name: dict[str, str],
    selected_keys: list[str],
) -> list[Resource]:
    resources = []
    for key_text in selected_keys:
        entry = xc_strings[key_text]
        if lang != "en" and not entry_should_translate(entry):
            continue
        result = localized_value(entry, lang, key_text)
        if result is None:
            continue
        simple, plural = result
        name = key_to_name[key_text]
        if plural is not None:
            converted = {q: convert_value(v) for q, v in plural.items()}
            resources.append(Resource(name, None, converted))
        else:
            resources.append(Resource(name, convert_value(simple), None))
    resources.sort(key=lambda r: r.name)
    return resources


def render_resource(r: Resource) -> str:
    if r.plural is not None:
        order = ["zero", "one", "two", "few", "many", "other"]
        items = "\n".join(
            f'        <item quantity="{q}">{r.plural[q]}</item>'
            for q in order
            if q in r.plural
        )
        return f'    <plurals name="{r.name}">\n{items}\n    </plurals>'
    return f'    <string name="{r.name}">{r.simple}</string>'


def render_locale_file(resources: list[Resource]) -> str:
    body = "\n".join(render_resource(r) for r in resources)
    return GENERATED_HEADER + "<resources>\n" + body + "\n</resources>\n"


def merge_into_english(existing_path: Path, resources: list[Resource]) -> str:
    """Append (or refresh) the generated block inside the existing,
    hand-authored values/strings.xml, leaving every other line alone."""
    content = existing_path.read_text(encoding="utf-8") if existing_path.exists() else "<resources>\n</resources>\n"

    block_lines = [GENERATED_BLOCK_START]
    block_lines.extend(render_resource(r) for r in resources)
    block_lines.append(GENERATED_BLOCK_END)
    block = "\n".join(block_lines)

    if GENERATED_BLOCK_START in content:
        pattern = re.compile(
            re.escape(GENERATED_BLOCK_START) + r".*?" + re.escape(GENERATED_BLOCK_END),
            re.S,
        )
        content = pattern.sub(block, content, count=1)
    else:
        marker = "</resources>"
        idx = content.rindex(marker)
        # Keep a blank line before the new block, matching the file's
        # existing section-separation style.
        prefix = content[:idx].rstrip("\n") + "\n\n"
        content = prefix + block + "\n" + content[idx:]
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write anything; exit nonzero if regenerating would change files on disk.",
    )
    args = parser.parse_args()

    if not args.source.exists():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 2

    xc = json.loads(args.source.read_text(encoding="utf-8"))
    xc_strings: dict = xc["strings"]

    existing_by_value = load_existing_android_strings(STRINGS_EN)
    used_names = existing_resource_names(STRINGS_EN)
    name_map = load_name_map(NAME_MAP_PATH)
    used_names |= set(name_map.values())

    # Only keys with *some* renderable English content are worth a
    # resource at all -- a handful of xcstrings entries are pure
    # cross-language format fragments (e.g. "%lld") with no localizations
    # dict whatsoever, and are skipped.
    selected_keys: list[str] = []
    key_to_name: dict[str, str] = {}
    from_map, matched, generated = 0, 0, 0
    for key_text, entry in xc_strings.items():
        if not entry.get("localizations") and key_text.strip("%@lldu ") == "":
            continue
        result = localized_value(entry, "en", key_text)
        if result is None:
            continue

        # The persistent map is authoritative once a key has a name: value
        # matching below can't rediscover it for any key with a format
        # specifier (Apple "%@" never reappears in the converted Android
        # value), so without this a previously generated name would drift
        # to a new hash suffix on every single run. See load_name_map's
        # docstring.
        if key_text in name_map:
            name = name_map[key_text]
            from_map += 1
        else:
            existing_name = existing_by_value.get(key_text)
            if existing_name:
                name = existing_name
                matched += 1
            else:
                base = slugify(key_text)
                name = base
                if name in used_names:
                    suffix = hashlib.sha1(key_text.encode("utf-8")).hexdigest()[:6]
                    name = f"{base}_{suffix}"
                used_names.add(name)
                generated += 1
            name_map[key_text] = name
        selected_keys.append(key_text)
        key_to_name[key_text] = name

    selected_keys.sort()

    outputs: dict[Path, str] = {}
    outputs[NAME_MAP_PATH] = render_name_map(name_map)
    en_resources = build_resources_for_locale("en", xc_strings, key_to_name, selected_keys)
    outputs[STRINGS_EN] = merge_into_english(STRINGS_EN, en_resources)

    coverage: dict[str, tuple[int, int]] = {}
    for lang in NON_ENGLISH:
        resources = build_resources_for_locale(lang, xc_strings, key_to_name, selected_keys)
        out_dir = REPO_ROOT / "app" / "src" / "main" / "res" / LOCALE_DIRS[lang]
        outputs[out_dir / "strings.xml"] = render_locale_file(resources)
        coverage[lang] = (len(resources), len(selected_keys))

    # A static (execution-order-independent) classification for the
    # report: whether each key's final name was adopted from an existing
    # hand-authored resource or newly minted for this corpus. Deliberately
    # not the from_map/matched/generated run-local counters above --
    # those describe what *this particular run* had to do given
    # whatever was already on disk/in the map, which varies by history
    # even though the resulting names are stable; the report should only
    # describe the stable, converged result so reruns are byte-identical.
    hand_authored_count = sum(1 for n in key_to_name.values() if not n.startswith("xc_"))
    corpus_generated_count = len(key_to_name) - hand_authored_count

    report_lines = [
        "P13 xcstrings -> Android mapping report",
        f"source: {args.source}",
        f"total xcstrings keys considered: {len(selected_keys)}",
        f"  under an existing hand-authored resource name: {hand_authored_count}",
        f"  under a generated xc_-prefixed name: {corpus_generated_count}",
        "",
        "per-language coverage (translated / total selected keys):",
    ]
    for lang in NON_ENGLISH:
        n, total = coverage[lang]
        report_lines.append(f"  {lang:<10} {n:>3} / {total}")
    report_lines.append("")
    report_lines.append("key -> android resource name:")
    for key_text in selected_keys:
        report_lines.append(f"  {key_text!r} -> {key_to_name[key_text]}")
    report = "\n".join(report_lines) + "\n"

    outputs[REPORT_PATH] = report

    if args.check:
        changed = []
        for path, new_content in outputs.items():
            old_content = path.read_text(encoding="utf-8") if path.exists() else None
            if old_content != new_content:
                changed.append(path)
        if changed:
            print("xcstrings_to_strings --check: would change:", file=sys.stderr)
            for p in changed:
                print(f"  {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print("xcstrings_to_strings --check: up to date")
        return 0

    for path, new_content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_content, encoding="utf-8")

    print(f"wrote {len(outputs) - 1} resource file(s) + mapping report + name map")
    print(f"  under hand-authored names: {hand_authored_count}, under generated xc_ names: {corpus_generated_count}")
    for lang in NON_ENGLISH:
        n, total = coverage[lang]
        print(f"  {lang:<10} {n:>3} / {total} translated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
